# Generated by Django 5.0.2 on 2024-05-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('agency_admin', 'Agency Admin'), ('branch_admin', 'Branch Admin'), ('default', 'Default')], default='default', max_length=50),
        ),
    ]
