# Generated by Django 5.0.2 on 2024-07-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_excursions', '0002_alter_excursion_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
