# Generated by Django 5.0.2 on 2024-07-27 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_excursions', '0003_alter_excursion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
