# Generated by Django 5.0.2 on 2024-08-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_excursions', '0006_excursion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='places',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], default='draft', max_length=10),
        ),
    ]
