# Generated by Django 5.0.2 on 2024-08-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_excursions', '0008_excursionorganizer_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api_excursions.excursion')),
            ],
            options={
                'ordering': ['media_type'],
            },
        ),
    ]
