# Generated by Django 5.0.2 on 2024-08-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_excursions', '0009_excursionmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionmedia',
            options={'ordering': ['media_type', 'created_at']},
        ),
    ]
