# Generated by Django 5.0.2 on 2024-02-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0001_initial'),
        ('api_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('postpointed', 'Postpointed')], default='postpointed', max_length=50)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_agency.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_main.profile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_agency.vehicle')),
            ],
        ),
    ]
