# Generated by Django 5.0.2 on 2024-02-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('refused', 'Refused'), ('postponed', 'Postponed')], default='postpointed', max_length=50),
        ),
    ]
