# Generated by Django 5.0.2 on 2024-03-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='imges/vehicles//%y/%m/%d'),
        ),
    ]
