# Generated by Django 5.0.2 on 2024-04-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0003_remove_branch_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
