# Generated by Django 5.0.2 on 2024-04-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0004_alter_branch_latitude_alter_branch_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=50, null=True),
        ),
    ]
