# Generated by Django 5.0.2 on 2024-03-16 13:49

import api_agency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0005_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to=api_agency.models.vehicle_image_path),
        ),
    ]
