# Generated by Django 5.0.2 on 2024-04-24 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0005_alter_branch_latitude_alter_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_fuel_full',
            field=models.BooleanField(default=False, help_text='Fuel status of the vehicle (True if full, False if not full)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_mileage_unlimited',
            field=models.BooleanField(default=False, help_text='Mileage status of the vehicle (True if unlimited, False if limited)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_with_driver',
            field=models.BooleanField(default=False, help_text='Indicates whether the vehicle is rented with a driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_rental_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Maximum number of rental days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_rental_age',
            field=models.PositiveSmallIntegerField(default=25, help_text='Minimum age required to rent the vehicle', validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='min_rental_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Minimum number of rental days', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
