# Generated by Django 5.0.2 on 2024-04-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0006_vehicle_is_fuel_full_vehicle_is_mileage_unlimited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('ar_name', models.CharField(blank=True, max_length=200)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_agency.wilaya'),
        ),
    ]
