# Generated by Django 5.0.2 on 2024-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0007_wilaya_branch_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
