# Generated by Django 5.0.2 on 2024-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0011_alter_rate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
