# Generated by Django 5.0.2 on 2024-05-06 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0015_remove_reservation_agency_reservation_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_reservations', to='api_agency.agency'),
        ),
    ]
