# Generated by Django 5.0.2 on 2024-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0017_plan_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='unlimited_branches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited_vehicles',
            field=models.BooleanField(default=False),
        ),
    ]
