# Generated by Django 5.0.2 on 2024-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0018_plan_unlimited_branches_plan_unlimited_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_at',
            field=models.DateTimeField(),
        ),
    ]
