# Generated by Django 5.0.2 on 2024-05-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0020_alter_notification_options_alter_reservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
    ]
