# Generated by Django 5.0.2 on 2024-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0021_alter_notification_options_alter_reservation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='image',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='url',
            field=models.URLField(blank=True, default='https://placehold.co/600x400', null=True),
        ),
    ]
