# Generated by Django 5.0.2 on 2024-05-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0022_remove_vehicleimage_image_vehicleimage_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
