# Generated by Django 5.0.2 on 2024-05-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0023_alter_vehicleimage_options_vehicleimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='LocationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='https://placehold.co/600x400', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api_agency.wilaya')),
            ],
        ),
    ]
