# Generated by Django 5.0.2 on 2024-06-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0026_reservation_protection_reservation_protection_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_new_subscriptions', to='api_agency.agency')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_agency.plan')),
            ],
        ),
    ]
