# Generated by Django 5.0.2 on 2024-06-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0027_newsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
