# Generated by Django 5.0.2 on 2024-07-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0030_alter_rate_agency_alter_rate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reason',
            field=models.CharField(choices=[('regular travel', 'Regular travel'), ('business', 'Business'), ('vacations', 'Vacations'), ('special event', 'Special event'), ('road trip', 'Road trip')], default='regular travel', max_length=50),
        ),
    ]
