# Generated by Django 5.0.2 on 2024-07-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0031_reservation_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['-rate']},
        ),
    ]
