# Generated by Django 5.0.2 on 2024-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_agency', '0032_alter_agency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='treated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
